<?php include("../../funciones.php");

try{ 
    
    if ($_POST){
        ini_set("soap.wsdl_cache_enabled", "0");
        $id_sucursal =  $_POST["CmbSUCURSALES"]; 
		$Moneda = $_POST["CmbMoneda"];
        $Id_Cliente = $_POST["TxtClave"];
        
        
        //parametros de la llamada
        $parametros = array();
        $parametros['sId_Empresa'] = $Empresa;
        $parametros['sMoneda'] = $Moneda;
        $parametros['sid_sucursal'] = $id_sucursal;
        $parametros['sId_Cliente'] = $Id_Cliente;
        //ini_set("soap.wsdl_cache_enabled", "0");
        //Invocación al web service
        $WS = new SoapClient($WebService, $parametros);
        //recibimos la respuesta dentro de un objeto
        $result = $WS->Saldos_ClientesXVendedor($parametros);
        $xml = $result->Saldos_ClientesXVendedorResult->any;
        $obj = simplexml_load_string($xml);
        $Datos = $obj->NewDataSet->Table;
    }
    else{}
} catch(SoapFault $e){
  var_dump($e);
}

    echo "<div class='table-responsive'>
        <table id='grid' class='table table-striped table-bordered table-condensed table-hover display compact' cellspacing='0' width='100%' ><tfoot><tr><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th></tr></tfoot></table></div>";

	$arreglo = [];
	for($i=0; $i<count($Datos); $i++){
		$arreglo[$i]=$Datos[$i];
	}

?>

     <script type="text/javascript"> 
        var datos = <?php echo json_encode($arreglo);?> ;
        
		<?php
        /*
			$sGridNomb = '#grid';
			$sWsNomb = 'vtas_netas';
			$aColumnas = array("nombre","VtasNetas","AbonosFactMes","TotalCobradoMes");
			$aTitulos = array("nombre","Ventas netas","Abonos Mes","Total Mes");
			echo GrdRptShort($sGridNomb,$sWsNomb,$aColumnas,$aTitulos);
        */
        /*
        	$sGridNomb = '#grid';
			$sWsNomb = 'vtas_netas';
			$aColumnas = array("nombre","VtasNetas","AbonosFactMes","TotalCobradoMes");
			$aTitulos = array("nombre","Ventas netas","Abonos Mes","Total Mes");
        
        */
		?>

   $(document).ready(function() {
         var table = $('#grid').DataTable({
            data:datos,
            columns: [
                { data: 'ID_SUCURSAL' },
                { data: 'ID_CLIENTE' },
                { data: 'NOMBBRE_CLI' },
                { data: 'SALDOXAPLICAR' },
                { data: 'SALDOTOTAL' },
                { data: 'SALDONORMAL' },
                { data: 'SALDOVENCIDO' },
                { data: 'SALDO1' },
                { data: 'SALDO2' },
                { data: 'SALDO3' },
                { data: 'SALDO4' },
                { data: 'SALDO5' }
            ],
            columnDefs: [
                { 'title': 'SUCURSAL',className: "text-left", 'targets': 0},
                { 'title': 'ID', className: "text-left", 'targets': 1},
                { 'title': 'CLIENTE', className: "text-left", 'targets': 2},
                { 'title': 'SALDO X APLICAR', className: "text-left", 'targets': 3},
                { 'title': 'SALDO TOTAL',className: "text-left", 'targets': 4},
                { 'title': 'SALDO NORMAL', className: "text-left", 'targets': 5},
                { 'title': 'SALDO VENCIDO', className: "text-left", 'targets': 6},
                { 'title': '1-7',className: "text-left", 'targets': 7},
                { 'title': '8-15', className: "text-left", 'targets': 8},
                { 'title': '16-23', className: "text-left", 'targets': 9},
                { 'title': '24-30', className: "text-left", 'targets': 10},
                { 'title': '31 Y MAS', className: "text-left", 'targets': 11}
            ],
            'createdRow': function ( row, data, index ) {
/*                $(row).attr({ id:data.id_Vendedor});
                $(row).addClass('vendedor');*/
            },  
            dom: 'lfBrtip', 
            paging: false,
            searching: true,
            ordering: false,
            buttons: [
                {
                    extend: 'copy',
                    message: 'PDF created by PDFMake with Buttons for DataTables.',
                    text: 'Copiar',
                    exportOptions: {
                        modifier: {
                            page: 'all'
                        }
                    }
                },
                {
                    extend: 'pdf',
                    text: 'PDF',
                    customize: function ( doc ) {
                        // Splice the image in after the header, but before the table
                        doc.content.splice( 1, 0, {
                            
                            alignment: 'center'
                        } );
                        // Data URL generated by http://dataurl.net/#dataurlmaker
                    },
                    filename: '".$sWsNomb."',
                    extension: '.pdf',       
                    exportOptions: {
                        columns: ':visible',
                        modifier: {
                            page: 'all'
                        }
                    }
                },
                {
                    extend: 'csv',
                    text: 'CSV',
                    header:'true',
                    filename: '".$sWsNomb."',
                    extension: '.csv',       
                    exportOptions: {
                        columns: ':visible',
                        modifier: {
                            page: 'all'
                        }
                    }
                },
                {
                    extend: 'excel',
                    message: 'PDF creado desde el sistema en linea del tayco.',
                    text: 'XLS',
                    filename: '".$sWsNomb."',
                    extension: '.xlsx', 
                    exportOptions: {
                        columns: ':visible',
                        modifier: {
                            page: 'all'
                        }
                    },
                    customize: function( xlsx ) {
                        var sheet = xlsx.xl.worksheets['sheet1.xml'];
                        $('row:first c', sheet).attr( 's', '42' );
                    }
                },
                {
                    extend: 'print',
                    message: 'PDF creado desde el sistema en linea del tayco.',
                    text: 'Imprimir',
                    exportOptions: {
                        stripHtml: false,
                        modifier: {
                            page: 'all'
                        }
                    }
                },
            ],
            'pagingType': 'full_numbers',
            'lengthMenu': [[-1], ['Todo']],
            'language': {
                'sProcessing':    'Procesando...',
                'sLengthMenu':    'Mostrar _MENU_ registros',
                'sZeroRecords':   'No se encontraron resultados',
                'sEmptyTable':    'Ningún dato disponible en esta tabla',
                'sInfo':          'Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros',
                'sInfoEmpty':     'Mostrando registros del 0 al 0 de un total de 0 registros',
                'sInfoFiltered':  '(filtrado de un total de _MAX_ registros)',
                'sInfoPostFix':   '',
                'sSearch':        'Buscar:',
                'sUrl':           '',
                'sInfoThousands':  ',',
                'sLoadingRecords': 'Cargando...',
                'oPaginate': {
                    'sFirst':    'Primero',
                    'sLast':    'Último',
                    'sNext':    'Siguiente',
                    'sPrevious': 'Anterior'
                },
                'oAria': {
                    'sSortAscending':  ': Activar para ordenar la columna de manera ascendente',
                    'sSortDescending': ': Activar para ordenar la columna de manera descendente'
                },
            'scrollY':        '60vh',
            'scrollX':        'true',
            'paging':         false
            }
 
        } );
        $('#txtbusqueda').on('keyup change', function() {
          //clear global search values
          table.search('');
          table.column($(this).data('columnIndex')).search(this.value).draw();
        });

        $(".dataTables_filter input").on('keyup change', function() {
          //clear column search values
          table.columns().search('');
          //clear input values
          $('#txtbusqueda').val('');
        });
    } );
        
    </script>